// *****************************************************************************
// Copyright (c) 2014, 2015, 2016, 2017 Pay With Privacy, Inc. All rights reserved.
// Authors:
// Jason Kruse   (jason@privacy.com)
// David Nichols (david@privacy.com)
// Boling Jiang  (boling@privacy.com)
// Felippe Nardi (felippe@privacy.com)
// *****************************************************************************
var _doPost,extensionID="djEuMC4x",tfaDeviceID=null;function isBeta(){return"beta"===window.environment}
if("undefined"!==typeof exports){Store=require("Store").Store;var Request=require("sdk/request").Request;_doPost=function(d,c,a,b,f){a=a||{};b=b||function(){};a.extensionID=extensionID;var e={};e["x-extension-id"]=extensionID;e["x-extension-version"]=chrome.runtime.getManifest().version;isBeta()&&(e["x-extension-beta"]="true");f&&(e.Authorization="Bearer "+f);a=Request({url:c,content:a,headers:e,onComplete:function(a){if(!c.match(/google\-analytics\.com/g)){a=a||{};var e=a.json&&null!==a.json?a.json:
{};e.status=a.status;e.token?Store.set("authToken",e.token,function(){b(e)}):b(e)}}});"GET"===d?a.get():a.post()}}else _doPost=function(d,c,a,b,f){a=a||{};b=b||function(){};a.extensionID=extensionID;$.ajax({url:c,type:d,data:a,cache:!1,beforeSend:function(a){a.setRequestHeader("x-extension-id",extensionID);a.setRequestHeader("x-extension-version",chrome.runtime.getManifest().version);isBeta()&&a.setRequestHeader("x-extension-beta","true");f&&a.setRequestHeader("Authorization","Bearer "+f);tfaDeviceID&&
a.setRequestHeader("x-tfa-deviceid",tfaDeviceID)}}).success(function(a,c,d){a.status=a.status||200;if(c=d.getResponseHeader("x-tfa-deviceid"))tfaDeviceID=c,Store.set("tfaDeviceID",c);a.token?Store.set("authToken",a.token,function(){b(a)}):b(a)}).fail(function(a){var c=a.responseJSON?a.responseJSON:{};c.status=a.status||500;b(c)})};var Api;
(function(){Api=function(){function d(a,b,d,e){var f="https://privacy.com/"+a;e=e||"POST";b=b||{};a!=c.login?Store.get("authToken",function(a){_doPost(e,f,b,d,a)}):_doPost(e,f,b,d)}var c={login:"auth/local",logout:"auth/logout",tfa:"auth/local/tfa",oneTimeCode:"auth/local/code",user:"api/v1/user/me",signup:"api/v1/user",createVirtualCard:"api/v1/card",getCardList:"api/v1/card",preCreateCard:"api/v1/card/pre",addcreditcard:"api/v1/fund",fundlist:"api/v1/fund",bankaccountlist:"api/v1/bank",setCardAttributes:"api/v1/card/attributes",
sendEvent:"api/v1/event"};return{login:function(a,b){d(c.login,a,b)},tfa:function(a,b){d(c.tfa,a,b)},oneTimeCode:function(a,b){d(c.oneTimeCode,a,b)},user:function(a,b){d(c.user,a,b,"GET")},signup:function(a,b){a.source="extension";d(c.signup,a,b)},createVirtualCard:function(a,b){d(c.createVirtualCard,a,b)},getCardList:function(a,b){d(c.getCardList,a,b,"GET")},addcreditcard:function(a,b){d(c.addcreditcard,a,b)},fundlist:function(a,b){d(c.fundlist,a,b,"GET")},bankaccountlist:function(a,b){d(c.bankaccountlist,
a,b,"GET")},logout:function(a,b){d(c.logout,b,a,"POST");Store.clear(a)},preCreateCard:function(a,b){d(c.preCreateCard,a,b)},setCardAttributes:function(a,b){d(c.setCardAttributes,a,b)},sendEvent:function(a,b){d(c.sendEvent,a,b)},post:function(a,b,c){_doPost(a,b,c)}}};"undefined"!==typeof exports&&(exports.Api=Api)})();
