// *****************************************************************************
// Copyright (c) 2014, 2015, 2016, 2017 Pay With Privacy, Inc. All rights reserved.
// Authors:
// Jason Kruse   (jason@privacy.com)
// David Nichols (david@privacy.com)
// Boling Jiang  (boling@privacy.com)
// Felippe Nardi (felippe@privacy.com)
// *****************************************************************************
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,d){a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var f=a[e];if(b.call(d,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};
$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6-impl","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("Object.assign",function(a){return a?a:function(a,d){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var f in e)$jscomp.owns(e,f)&&(a[f]=e[f])}return a}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=
!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),
a[b]=null;this.onSettledCallbacks_=null}};var e=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(h){f(h)}}:b}var e,f,g=new c(function(a,b){e=a;f=b});this.callWhenSettled_(d(a,e),
d(b,f));return g};c.prototype["catch"]=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?e.asyncExecute(c):this.onSettledCallbacks_.push(function(){e.asyncExecute(c)})};c.resolve=function(a){return a instanceof c?a:new c(function(b,c){b(a)})};c.reject=function(a){return new c(function(b,c){c(a)})};
c.race=function(a){return new c(function(b,d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c.resolve(f.value).callWhenSettled_(b,d)})};c.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c.resolve([]):new c(function(a,e){function g(b){return function(c){f[b]=c;k--;0==k&&a(f)}}var f=[],k=0;do f.push(void 0),k++,c.resolve(d.value).callWhenSettled_(g(f.length-1),e),d=b.next();while(!d.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(c.$jscomp$new$AsyncExecutor=function(){return new b});
return c},"es6-impl","es3");
angular.module("privacyApp",["privacyCommonApp","ui.router"]).config(["$urlRouterProvider","$httpProvider","$compileProvider",function(a,b,d){a.when("","/loading");b.interceptors.push("authInterceptor");b.interceptors.push("subscriptionRequiredInterceptor");d.aHrefSanitizationWhitelist(/^\s*(https?|extension|moz-extension|resource|chrome-extension):/)}]).config(["$stateProvider","$urlRouterProvider",function(a,b){a.state("home",{url:"/",templateUrl:"../routes/home/home.html",authenticate:!0,controller:"HomeController",
controllerAs:"Home"}).state("login",{url:"/login",templateUrl:"../routes/login/login.html",controller:"LoginController",controllerAs:"Login"}).state("card-details",{url:"/card-details",templateUrl:"../routes/card-details-page/card-details-page.html",authenticate:!0,controller:"CardDetailsPageController",controllerAs:"Page",params:{cardID:null}}).state("loading",{url:"/loading",templateUrl:"../routes/loading-page/loading-page.html",controller:"LoadingPageController",controllerAs:"Page"});b.otherwise("/login")}]).run(["$rootScope",
"$state","AuthService",function(a,b,d){a.$on("$stateChangeStart",function(a,e){if(e.authenticate)return d.isAuthenticated().then(function(c){c||(b.transitionTo("login"),a.preventDefault())})})}]).factory("authInterceptor",["$q","pwp","$rootScope","$injector","AuthService",function(a,b,d,c,e){return{request:function(b){var c=a.defer();b.headers=b.headers||{};-1<b.url.indexOf("api/")&&(b.url="https://privacy.com"+b.url);b.headers["x-extension-id"]="djEuMC4x";b.headers["x-extension-version"]=chrome.runtime.getManifest().version;
e.getAuthToken().then(function(a){a&&(b.headers.Authorization="Bearer "+a);e.getTFADeviceID().then(function(a){a&&(b.headers["x-tfa-deviceid"]=a);c.resolve(b)})});return c.promise},responseError:function(e){var f=c.get("$state");401===e.status&&(b.invoke("set",{userID:""}),b.invoke("set",{currentCardID:null}),b.invoke("set",{currentRoute:"login"}),b.invoke("set",{cardList:null}),b.invoke("set",{transactionList:null}),d.authenticated=!1,d.user={},f.go("login"));return a.reject(e)}}}]).factory("subscriptionRequiredInterceptor",
["$injector","$q","pwp",function(a,b,d){return{responseError:function(c){if(_.get(c,"data.subscriptionRequired")){var e=a.get("ConfirmService"),f=a.get("EventConstants"),m=a.get("openTab");e.confirm({title:"Upgrade Required",subtitle:"Please visit the Pricing page to upgrade.",cancelButtonText:"Cancel",confirmButtonText:"See Plans"}).then(function(a){a&&(d.invoke("event",{name:f.OBJECT_ACTIONS.CTA.CLICKED,data:{buttonContext:"Subscription Required Prompt",buttonName:"See Plans",context:"Popup"}}),
m("/pricing",function(){window.close()}))});d.invoke("event",{name:f.OBJECT_ACTIONS.MODAL.VIEWED,data:{modalName:"Subscription Required Prompt",context:"Popup"}})}return b.reject(c)}}}]).constant("API_HOST","https://privacy.com");angular.module("privacyApp").constant("EventConstants",{OBJECT_ACTIONS:{CTA:{CLICKED:"CTA: Clicked"},MODAL:{VIEWED:"Modal: Viewed"},CARD:{SELECTED:"Card: Selected"},EXTENSION:{DETECTED:"Extension: Detected Checkout Form",OPENED:"Extension: Opened",DISMISSED:"Extension: Dismissed"}}});
angular.module("privacyApp").controller("InterstitialCtrl",["$scope","$document","$q","pwp","$uibModal","openTab","ModalService","ConfirmService","EventConstants",function(a,b,d,c,e,f,m,k,l){function n(){d(function(a){c.invoke("user",{},function(b){a(b)})}).then(function(b){a.interstitialUser=b})}a.callingOrigin=null;var g=new Date((new Date(new Date)).setMonth((new Date).getMonth()+48)),g=("0"+(g.getMonth()+1)).slice(-2)+"/"+(""+g.getFullYear()).slice(-2);a.card={type:"MERCHANT_LOCKED",expires:g};
window.addEventListener("message",function(b){if(b&&b.data){b.data.caller&&(a.callingOrigin=b.data.caller);401==b.data.status?a.authenticated=!1:b.data.error&&(e.open({controller:"ModalConfirmController",controllerAs:"modal",templateUrl:"components/modal-confirm/modal-confirm.html",resolve:{options:{title:"Whoops!",subtitle:b.data.error,confirmButtonText:"Got it",confirmButtonCallback:a.closeCreateCard}}}),a.createCardWaiting=!1,a.preCreatePending=!1,a.card.tfaResponse="",a.card.rememberDevice=null);
b.data.subscriptionRequired&&(k.confirm({title:"Upgrade Required",subtitle:"Please visit the Pricing page to upgrade.",cancelButtonText:"Cancel",confirmButtonText:"See Plans"}).then(function(a){a&&(c.invoke("event",{name:l.OBJECT_ACTIONS.CTA.CLICKED,data:{buttonContext:"Subscription Required Prompt",buttonName:"See Plans",context:"Interstitial"}}),f("/pricing",function(){window.close()}))}),c.invoke("event",{name:l.OBJECT_ACTIONS.MODAL.VIEWED,data:{modalName:"Subscription Required Prompt",context:"Interstitial"}}),
a.createCardWaiting=!1,a.preCreatePending=!1,a.card.tfaResponse="",a.card.rememberDevice=null);b.data.tfa&&(a.createCardWaiting=!1,a.userToken=b.data.tfa,a.tfaResponse="",m.show("tfa",{rememberDevice:a.card.rememberDevice,tfaResponse:a.card.tfaResponse,onSubmit:function(b,c){var d=c.tfaResponse,g=void 0===c.rememberDevice?!1:c.rememberDevice;a.card.tfaResponse=d;a.card.rememberDevice=g;d&&a.createCard()}}));b.data.useParent&&(a.useParent=!0);if(b.data.preCreateCard){delete a.preCreatePending;var d=
b.data.preCreateCard;a.cardStyle=d.style;a.fundingSources=d.bankAccountList;a.existingCardList=(d.existingCardList||[]).filter(function(a){return"CLOSED"!==a.state}).map(function(a){a.hostname&&(a.style=d.style);a.created=new Date(a.created);a.spendLimit=Number(a.spendLimit);1>a.spendLimit&&(a.spendLimit=null);return a});a.existingCardList.length?a.VIEW_STATE="EXISTING":(d.style?a.card.style=d.style:d.hostname&&(a.card.hostname=d.hostname),a.VIEW_STATE="CREATE")}a.$apply()}},!1);b.bind("keydown",
function(d){var g=b.find(".modal-content").length;"Escape"!==d.key&&"Escape"!==d.code||g||(c.invoke("event",{name:l.OBJECT_ACTIONS.EXTENSION.DISMISSED,data:{context:"Interstitial"}}),(a.useParent?window.parent:window.top).postMessage({invoke:"closeCreateCard"},a.getMessageDestination()))});a.init=function(){a.appLoaded=!0;a.authtokenResolved=!1;d(function(a){c.invoke("get","authToken",function(b){a(!!b)})}).then(function(b){a.authtokenResolved=!0;(a.authenticated=b)&&a.preCreateCard()});c.invoke("event",
{name:l.OBJECT_ACTIONS.EXTENSION.OPENED,data:{context:"Interstitial"}})};a.init();a.handleLogin=function(b){a.authenticated=!0;a.user=b;c.invoke("set",{userID:b.id});a.preCreateCard()};a.handleTFACancel=function(){a.tfaCardCreate=!1};a.selectCard=function(b){a.card=Object.assign({},b);a.card.hostname&&(a.card.style=a.cardStyle);a.VIEW_STATE="CREATE"};a.back=function(){a.card={};a.VIEW_STATE="EXISTING"};a.newCard=function(){a.card={unused:!0,type:"MERCHANT_LOCKED",spendLimitDuration:"MONTHLY"};a.card.style=
a.cardStyle;a.VIEW_STATE="CREATE"};a.getCreateCardButtonText=function(a){return a.created?("PAUSED"==a.state?"Unpause & ":"")+"Use Card":"Create Card"};a.createCard=function(b){a.createCardWaiting=!0;a.card.fundingSource&&(a.card.bankAccountID=a.card.fundingSource.bankAccountID);var d=!1;a.card&&a.card.cardID?("PAUSED"==a.card.state&&(a.card.state="OPEN"),d=(a.existingCardList||[]).reduce(function(b,c){return c.cardID==a.card.cardID?JSON.stringify(a.card)!=JSON.stringify(c):b},!1),c.invoke("event",
{name:l.OBJECT_ACTIONS.CARD.SELECTED,data:{cardType:"Existing"}})):c.invoke("event",{name:l.OBJECT_ACTIONS.CARD.SELECTED,data:{cardType:"New"}});b&&b.tfaResponse&&(a.card.tfaResponse=b.tfaResponse,a.card.rememberDevice=b.rememberDevice);(a.useParent?window.parent:window.top).postMessage({invoke:"createCard",card:a.card,modifiedExistingCard:d},a.getMessageDestination())};a.tfa=function(){if(!a.tfaResponse||0===a.tfaResponse.length)return e.open({controller:"ModalConfirmController",controllerAs:"modal",
templateUrl:"components/modal-confirm/modal-confirm.html",resolve:{options:{title:"Please enter your TFA token",confirmButtonText:"Got it"}}});a.card.tfaResponse=a.tfaResponse;a.card.rememberDevice=a.rememberDevice;(a.useParent?window.parent:window.top).postMessage({invoke:"createCard",card:a.card},a.getMessageDestination())};a.getMessageDestination=function(){return!a.callingOrigin||a.callerIsIframe?"*":a.callingOrigin};a.closeCreateCard=function(){c.invoke("event",{name:l.OBJECT_ACTIONS.EXTENSION.DISMISSED,
data:{context:"Interstitial"}});(a.useParent?window.parent:window.top).postMessage({invoke:"closeCreateCard"},a.getMessageDestination())};a.selectText=function(a){a.target.setSelectionRange(0,a.target.value.length)};a.preCreateCard=function(){n();a.preCreatePending=!0;(a.useParent?window.parent:window.top).postMessage({invoke:"preCreateCard"},a.getMessageDestination())};if(g=(a.callingOrigin||"").match(/:\/\/(.+)/))a.card.name=g[1]}]);
(function(){angular.module("privacyApp").controller("PopupCtrl",["$scope","$rootScope","$q","$timeout","$state","pwp","toast","openTab","CardService","TransactionService","EventConstants",function(a,b,d,c,e,f,m,k,l,n,g){a.openTab=k;a.resetUser=function(){b.user={email:"",password:""}};a.resetUser();a.user=b.user;b.$watch(function(){return b.user},function(){a.user=b.user});b.$watch(function(){return b.authenticated},function(){a.authenticated=b.authenticated});a.isState=function(a){return e.is(a)};
a.VIEW_STATES={LOGIN:"login"};a.loginHandler=function(b){a.init();n.reset();l.reset();f.invoke("set",{userID:b.id});e.go("home")};a.searchText="";a.onSearchTextChange=function(b){a.searchText=b};a.searching=!1;a.onSearchingChange=function(b){a.searching=b};a.tfaCancelHandler=function(){b.user.tfaResponse="";a.tfaCardCreate=!1};a.init=function(c){f.invoke("event",{name:g.OBJECT_ACTIONS.EXTENSION.OPENED,data:{context:"Popup"}});b.authenticated=!1;var k={authenticated:!1,resize:c||!1,viewState:a.VIEW_STATES.LOGIN};
d(function(c,g){f.invoke("get","authToken",function(g){if(!g)return e.go("login"),c(k);k.authenticated=!0;f.invoke("get","currentRoute",function(g){g==a.VIEW_STATES.LOGIN&&(g=!1);g=g||"home";"card-details"===g?f.invoke("get","currentCardID",function(a){e.go("card-details",{cardID:a})}):e.go(g);d(function(a){f.invoke("user",{},function(b){a(b)})}).then(function(a){b.user=a;b.$broadcast("user-update")});n.getTransactions();c(k)})})}).then(function(a){a.authenticated&&(b.authenticated=!0)})};a.init()}])})();
function g_reload(){angular.element(document.body).scope().init(!0)}/Macintosh.*Chrome\/66/.test(navigator.userAgent)&&document.addEventListener("DOMContentLoaded",function(){var a=document.body.clientHeight;document.body.style.height=a+1+"px";setTimeout(function(){return document.body.style.height=a+2+"px"},50)});
angular.module("privacyApp").factory("AuthService",["pwp","$rootScope",function(a,b){return{getAuthToken:function(){return new Promise(function(b){a.invoke("get","authToken",function(a){b(a||!1)})})},getTFADeviceID:function(){return new Promise(function(b){a.invoke("get","tfaDeviceID",function(a){b(a||!1)})})},isAuthenticated:function(){return new Promise(function(b,c){a.invoke("get","authToken",function(a){if(!a)return b(!1);b(!0)})})}}}]);
(function(){angular.module("privacyApp").filter("getHostname",function(){return function(a){var b=document.createElement("a");b.href=a;return b.hostname}});angular.module("privacyApp").filter("timePeriodToNoun",function(){return function(a){if(a){switch(a.toUpperCase()){case "ANNUALLY":a="per year";break;case "MONTHLY":a="per month";break;case "WEEKLY":a="per week";break;case "TRANSACTION":a="per transaction";break;case "FOREVER":a="total"}return a}}})})();"use strict";
angular.module("privacyApp").factory("testImage",["$q",function(a){return{tryUrl:function(b){if(b){var d=a.defer(),c=angular.element(new Image);c.bind("load",function(){d.resolve(b)});c.bind("error",function(){d.reject(b)});c.attr("src",b);return d.promise}}}}]);
angular.module("privacyApp").factory("UserService",["pwp","$rootScope","CardService","TransactionService",function(a,b,d,c){return{logout:function(){return new Promise(function(e){a.invoke("logout",{},function(){a.invoke("set",{userID:""});a.invoke("set",{currentCardID:null});a.invoke("set",{cardList:null});a.invoke("set",{transactionList:null});c.reset();d.reset();b.authenticated=!1;b.user={};e()})})}}}]);
(function(){angular.module("privacyApp").directive("auth",["$http","API_HOST","$rootScope","$q","$sce","$timeout","pwp","toast","openTab","$window",function(a,b,d,c,e,f,m,k,l,n){return{restrict:"E",replace:!0,scope:{tfaOnly:"=",onSuccess:"=",onTfaCancel:"=",onCreateCardTfa:"="},templateUrl:"/components/auth/auth.html",link:function(a){function g(d,e){a.loading=!0;k.empty();var g,f=a.$watch(function(){return document.getElementById("captchaIframe")&&document.getElementById("captchaIframe")},function(a){a&&
(g=a,g.onload=function(){g.contentWindow.postMessage({},b)},f())});c(function(a){m.invoke(d,e,function(b){a(b)})}).then(function(c){a.promptCaptcha&&g.contentWindow.postMessage({action:"resetCaptcha"},b);c.token&&c.id?(m.invoke("set",{userID:c.id,codeData:{}}),a.onSuccess(c),a.promptCaptcha=!1):(a.resetState(),a.loading=!1,c.message&&/captcha/i.test(c.message)?(a.promptCaptcha=!0,k.error(c.message)):c.message&&!c.userToken?k.error(c.message):(c.twoFactorAuth||c.oneTimeCode)&&c.userToken?(a.user.userToken=
c.userToken,a.authState="TFA",a.oneTimeCode=c.oneTimeCode,m.invoke("set",{codeData:{userToken:c.userToken,oneTimeCode:c.oneTimeCode,twoFactorAuth:c.twoFactorAuth}})):!c||c&&500==c.status?k.error("There was a problem completing your request. Please try again."):401==c.status?k.error("Incorrect email or password."):a.user.token&&403==c.status&&k.error("Incorrect code. Please try again."))})}m.invoke("get","codeData",function(b){var c=void 0===b?{}:b;b=c.userToken;var d=c.oneTimeCode,c=c.twoFactorAuth;
(d||c)&&b&&(a.user.userToken=b,a.authState="TFA",a.oneTimeCode=d)});n.addEventListener("message",function(b){b.data&&b.data.captchaResponse&&(a.user.captchaResponse=b.data.captchaResponse)});a.captchaIframeUrl=e.trustAsResourceUrl(b+"/extension-captcha");a.openTab=function(a){l(a)};a.user=d.user;d.$watch(function(){return d.user},function(){a.user=d.user});a.$watch("tfaOnly",function(){a.authState=a.tfaOnly?"TFA":"LOGIN";a.loading=!1});a.resetState=function(){a.user.password="";a.user.token=""};a.login=
function(){g("login",a.user)};a.tfa=function(){if(a.user.token&&a.user.token.length){a.oneTimeCode&&(a.user.code=a.user.token);if(a.tfaOnly)return a.loading=!0,f(function(){a.loading=!1},1E3),a.onCreateCardTfa({token:a.user.token,rememberDevice:a.user.rememberDevice});g(a.oneTimeCode?"oneTimeCode":"tfa",a.user)}else k.error("Please enter your code")};a.tfaBack=function(){if(a.tfaOnly)a.onTfaCancel();else a.resetState(),m.invoke("set",{codeData:{}}),a.authState="LOGIN"}}}}])})();"use strict";
(function(){angular.module("privacyApp").directive("cdnImg",["testImage",function(a){return{restrict:"A",scope:{src:"=cdnImg",fallback:"=cdnImgFallback"},link:function(b,d){function c(){d.attr("src","https://cdn.privacy.com"+b.src)}function e(){a.tryUrl("https://privacy.com"+b.src).then(function(){d.attr("src","https://privacy.com"+b.src)},function(){b.fallback&&d.attr("src",b.fallback)})}function f(){e()}function m(){a.tryUrl("https://cdn.privacy.com"+b.src).then(c,f)}"/"!==b.src.charAt(0)?(e(),
console.log("cdn-img","Relative img src detected. Not cdnifying. Src=",b.src)):(m(),b.$watch("src",function(d,e){d&&d!==e&&a.tryUrl("https://cdn.privacy.com"+b.src).then(c,f);m()}));a.tryUrl("https://cdn.privacy.com"+b.src).then(c,f)}}}])})();
(function(){angular.module("privacyApp").directive("customSelect",["$timeout","getTotalOffset",function(a,b){return{restrict:"A",link:function(d,c,e){var f=angular.element(c[0].querySelector(".select-value"));f.on("focus",function(c){var d=c.target.parentElement.querySelector(".select-options");a(function(){var a=-.5*d.offsetHeight;d.style.marginTop=a+"px";var c=b(d).bottom;0>c&&(d.style.marginTop=c+a+"px")},0);angular.element(d).on("click",function(b){f.removeClass("-update");a(function(){f.addClass("-update")},
0)})})}}}])})();(function(){angular.module("privacyApp").directive("clickToCopy",["toast",function(a){return{restrict:"A",link:function(b,d,c){d.on("click",function(){var b=d[0];b.setSelectionRange(0,b.value.length);try{document.execCommand("copy"),b.setSelectionRange(0,0)}catch(f){return}a.empty();a.success("Copied to clipboard")})}}}])})();(function(){angular.module("privacyApp").directive("existingCards",function(){return{restrict:"E",scope:{cards:"=",onSelectCard:"="},templateUrl:"/components/existing-cards/existing-cards.html"}})})();
angular.module("privacyApp").controller("ModalCardDetailsController",["$uibModalInstance","pwp","$q","toast","$rootScope","CardService","options",function(a,b,d,c,e,f,m){function k(){a.close()}var l={closeModal:k,updateCard:function(a,b){l.loadingEditCard||(l.loadingEditCard=!0,f.update(b.cardID,b).then(function(){m.onCardUpdateSuccess();c.success("Edited Card!");k()})["catch"](function(){c.error("Error updating card")})["finally"](function(){l.loadingEditCard=!1}))},onClickEditCard:function(){l.editingCard=
!0},updateCardFromList:function(){f.getCards().then(function(a){if(a=a.cardList.all.find(function(a){return a.cardID===l.card.cardID}))l.card=a})},editingCard:!1,loadingEditCard:!1,newCardFundingSources:[],card:Object.assign({},m.card)||{}};(function(){d(function(a){b.invoke("bankAccountlist",{},function(b){a(b)})}).then(function(a){a&&a.bankAccountList&&(l.newCardFundingSources=a.bankAccountList)});e.$on("card-list-update",function(){l.updateCardFromList()})})();return l}]);
angular.module("privacyApp").controller("ModalTransactionDetailsController",["$uibModalInstance","pwp","$q","$scope","toast","TransactionService","ConfirmService","Toast","options",function(a,b,d,c,e,f,m,k,l){var n={closeModal:function(){a.close()},confirmHideTransaction:function(a){m.confirm({subtitle:"This can't be undone."}).then(function(b){b&&n.hideTransaction(a)})},hideTransaction:function(a){f.hide(a.transactionID).then(function(){n.closeModal();if(l.onHideTransactionSuccess)l.onHideTransactionSuccess()})},
transaction:l.transaction||{}};(function(){c.$watch(function(){return n.transaction},function(a){n.transaction=a})})();return n}]);
(function(){angular.module("privacyApp").directive("tooltipToggle",["$document","$timeout","toast","getTotalOffset",function(a,b,d,c){return{restrict:"C",transclude:!0,scope:{},templateUrl:"/components/tooltip/tooltip-toggle.html",link:function(d,f,m){f[0].querySelector(".callout");d.visible=!1;a.on("click",function(a){d.visible&&(d.visible=!1,d.$apply())});d.handleClick=function(a){var e=a.target.parentElement.querySelector(".tooltip"),f=a.target.parentElement.querySelector(".callout");b(function(){d.visible=
!d.visible;b(function(){var a=c(e).left;0>a&&(e.style.marginLeft=-1*a+"px",f.style.left=a+"px")},0)},0)}}}}])})();(function(){angular.module("privacyApp").directive("tooltip",function(){return{restrict:"C",transclude:!0,templateUrl:"/components/tooltip/tooltip.html"}})})();
angular.module("privacyApp").controller("PopupHeaderDirectiveController",["$rootScope","$scope","$state","UserService","ModalService","EventConstants","openTab","pwp",function(a,b,d,c,e,f,m,k){var l={onClickTabHandler:function(a){l.currentTab=a;l.onClickTab(a)},onClickLogoutHandler:function(){l.onClickLogout()},isState:function(a){return d.is(a)},onPressLogout:function(){c.logout().then(function(){d.go("login")})},onPressCreateCard:function(){e.show("card-create",{user:a.user,closeOnSuccess:!0,hideLimitSlider:"undefined"!==
typeof browser,onCreateSuccess:function(a){d.go("card-details",{cardID:a.cardID})}})},searchText:b.searchText,searching:b.searching,onClickTab:null,onClickLogout:null,currentTab:null,authenticated:a.authenticated,accountBalance:a.accountBalance,menu:[{label:"Go to Privacy.com",onClick:function(){m("/home",function(){window.close()})}},{label:"Log out",onClick:function(){l.onPressLogout()}}]};(function(){a.$watch(function(){return a.authenticated},function(){l.authenticated=a.authenticated});b.$watch(function(){return l.searchText},
function(a){b.onSearchTextChange(a)});b.$watch(function(){return l.searching},function(a){b.onSearchingChange(a)});a.$watch(function(){return a.accountBalance},function(a){l.accountBalance=a})})();return l}]);angular.module("privacyApp").directive("popupHeader",function(){return{restrict:"E",replace:!0,scope:!0,bindToController:{onClickTab:"<",currentTab:"<"},controller:"PopupHeaderDirectiveController",controllerAs:"Header",templateUrl:"components/popup-header/popup-header.html"}});
angular.module("privacyApp").controller("CardDetailsPageController",["$q","$rootScope","$scope","$stateParams","$timeout","pwp","CardService","TransactionService",function(a,b,d,c,e,f,m,k){function l(){f.invoke("get","cardList",function(a){a&&g.nonBlockingLoad&&(g.cardList=a,g.card=a.find(function(a){return c.cardID===a.cardID}));f.invoke("get","transactionList",function(a){a&&g.nonBlockingLoad&&(g.transactionList=a,g.card&&(g.loadingPage=!1))})})}function n(a){a={all:a.all.slice(0,10),declines:[]};
f.invoke("set",{transactionList:a})}var g={loadingPage:!0,nonBlockingLoad:!0,user:null,card:null,cardList:{all:[],open:[],closed:[]},transactionList:{all:[],declines:[]},hideLimitSlider:"undefined"!==typeof browser};e(function(){f.invoke("set",{currentRoute:"card-details"});f.invoke("set",{currentCardID:c.cardID});d.$watch(function(){return c.cardID},function(){c.cardID&&l()});g.user=b.user;a.all([m.getCards(),k.getTransactions()]).then(function(a){g.cardList=_.get(a[0],"cardList",g.cardList);g.transactionList=
_.get(a[1],"transactionList",g.transactionList);g.card=_.get(g,"cardList.all",[]).find(function(a){return c.cardID===a.cardID});g.loadingPage=!1;g.nonBlockingLoad=!1;f.invoke("set",{cardList:g.cardList.open.slice(0,10)});n(g.transactionList)});b.$on("user-update",function(){g.user=b.user})});return g}]);
angular.module("privacyApp").controller("HomeController",["$q","$scope","$rootScope","$state","pwp","$uibModal","ModalService","CardService","TransactionService",function(a,b,d,c,e,f,m,k,l){function n(){l.getTransactions().then(function(a){a=a.transactionList;h.transactionList=a;a={all:a.all.slice(0,10),declines:[]};e.invoke("set",{transactionList:a});h.loadingTransactions=!1;h.remoteTransactionsLoaded=!0;h.remoteCardsLoaded&&(h.nonBlockingLoad=!1)})}function g(){q();r();p(function(){var a=_.get(d.user,
"permissions",[]),b=_.get(d.user,"fundingCardList",[]);-1<a.indexOf("CARD_FUNDING")&&b.some(function(a){return"DELETED"!==a.state})&&(d.accountBalance=_.get(d.user,"accountBalances.available","0"));h.doingInitialLoad=!1;h.remoteCardsLoaded=!0;h.remoteTransactionsLoaded&&(h.nonBlockingLoad=!1)});n()}function q(){e.invoke("get","cardList",function(a){0<a.length&&!h.filteredCardList&&(h.filteredCardList=a,h.loadingCardList=!1,h.doingInitialLoad=!1)})}function r(){e.invoke("get","transactionList",function(a){a&&
!h.transactionList&&(h.transactionList=a,h.loadingTransactions=!1)})}function p(a){a=void 0===a?function(){}:a;h.errorLoadingCardList=!1;k.getCards().then(function(a){h.errorLoadingCardList=!1;h.cardList=a.cardList;e.invoke("set",{cardList:a.cardList.open.slice(0,10)});h.getCardsForCurrentTab();0===_.get(h,"cardList.open",[]).length&&0===_.get(h,"cardList.closed",[]).length?h.showingEmptyState=!0:h.showingEmptyState=!1;_.get(a,"cardList.all",[]).forEach(function(b){b.meta&&1<_.get(a,"cardList.all",
[]).length&&b.meta[k.GENERATED_FIRST_CARD]&&h.hideFirstCardPreview(b)});h.getRecentCard().then(function(){h.filteredCardList=_.get(h,"cardList.open",[]).filter(function(a){return h.recentCard?a.cardID!==h.recentCard.cardID:!0});h.getCardsForCurrentTab()})})["catch"](function(){h.errorLoadingCardList=!0})["finally"](function(){h.loadingCardList=!1;a()})}var h={onClickCard:function(a){c.go("card-details",{cardID:a.cardID});_.get(a,"meta."+k.GENERATED_FIRST_CARD)&&!_.get(a,"meta."+k.GENERATED_FIRST_CARD_SEEN)&&
(a.meta[k.GENERATED_FIRST_CARD_SEEN]=!0,k.update(a.cardID,a))},getCardList:p,getCardsForCurrentTab:function(){h.currentTabCardList=[];chrome.tabs.query({currentWindow:!0,active:!0},function(a){var c=(new URL(a[0].url)).hostname;h.currentTabCardList=_.get(h,"cardList.all",[]).filter(function(a){return"CLOSED"===a.state||h.recentCard&&a.cardID===h.recentCard.cardID?!1:a.hostname.length&&-1<c.indexOf(a.hostname)||a.memo.length&&-1<c.indexOf(String(a.memo).toLowerCase())||a.meta&&a.meta.hostname&&a.meta.hostname.length&&
-1<c.indexOf(a.meta.hostname)?!0:!1});b.$apply()})},getRecentCard:function(){var b=a.defer();e.invoke("get","card",function(a){try{if(!a||0===a.length)throw h.recentCard=null,Error("Recent card not found");a=JSON.parse(a);var c=_.get(h,"cardList.open",[]).find(function(b){return String(b.cardID)===String(a.cardID)});if(!c)throw Error("Card not found");if(c.created<+new Date-108E5)throw h.recentCard=null,Error("Card created too long ago");h.recentCard=c;b.resolve(h.recentCard)}catch(t){e.invoke("set",
{card:null}),b.resolve(null)}});return b.promise},onPressCreateCard:function(){m.show("card-create",{user:d.user,closeOnSuccess:!0,hideLimitSlider:"undefined"!==typeof browser,onCreateSuccess:function(a){c.go("card-details",{cardID:a.cardID})}})},onClickTransaction:function(a){f.open({controller:"ModalTransactionDetailsController",controllerAs:"modal",templateUrl:"components/modal-transaction-details/modal-transaction-details.html",resolve:{options:{transaction:a,preventHideTransaction:!0}}})},getTransactions:n,
doingInitialLoad:!1,nonBlockingLoad:!0,showingEmptyState:!1,searchText:b.searchText,searching:b.searching,errorLoadingCardList:!1,loadingCardList:!0,loadingTransactions:!0,remoteCardsLoaded:!1,remoteTransactionsLoaded:!1,cardList:{all:[],open:[],closed:[]},hideFirstCardPreview:function(a){h.hidePotentialFirstCardPreview=!0;a.meta&&a.meta[k.GENERATED_FIRST_CARD]&&!a.meta[k.GENERATED_FIRST_CARD_SEEN]&&(a.meta[k.GENERATED_FIRST_CARD_SEEN]=!0,k.update(a.cardID,a))},hidePotentialFirstCardPreview:!1,transactionList:null,
toggleDeclines:function(){h.showDeclines=!h.showDeclines},showDeclines:!1,filteredCardList:null,recentCard:null,accountBalance:d.accountBalance};(function(){e.invoke("set",{currentRoute:"home"});h.doingInitialLoad=!0;g();b.$watch(function(){return b.searchText},function(a){h.searchText=a});b.$watch(function(){return b.searching},function(a){h.searching=a});d.$watch(function(){return d.accountBalance},function(a){h.accountBalance=a})})();return h}]);
angular.module("privacyApp").controller("LoadingPageController",function(){return{}});angular.module("privacyApp").controller("LoginController",["$q","$scope","pwp",function(a,b,d){d.invoke("set",{currentRoute:"login"});return{}}]);
(function(){angular.module("privacyApp").factory("getTotalOffset",function(){function a(b){var d=b.offsetTop;var c=b.offsetLeft;b.offsetParent&&(d+=a(b.offsetParent).top,c+=a(b.offsetParent).left);return{top:d,bottom:window.innerHeight-b.offsetHeight-d,left:c,right:window.innerWidth-b.offsetWidth-c}}return a})})();
(function(){angular.module("privacyApp").factory("openTab",["pwp",function(a){return function(b,d){var c=0!==b.indexOf("http")||/privacy\.com/i.test(b);a.invoke("get","authToken",function(e){b=e&&c?"https://privacy.com/redirect/"+encodeURIComponent(JSON.stringify(e))+"/"+encodeURIComponent(b):b;a.log("Opening tab to URL: "+b);a.invoke("opentab",b);d&&d()})}}])})();
(function(){angular.module("privacyApp").factory("pwp",function(){return new Entity("popup","undefined"!==typeof self&&"undefined"!==typeof self.port?self.port:void 0)})})();
(function(){angular.module("privacyApp").factory("toast",["$timeout",function(a){function b(b){b.addClass("-remove");a(function(){b.remove()},500)}function d(c,d,f){var e=angular.element(document.querySelector(".toast-stack"));e&&e.length||(e=angular.element("<div></div>").addClass("toast-stack"),angular.element(document.body).append(e));c="ERROR"==c?"-error":"SUCCESS"==c?"-success":"-notify";var k=angular.element("<div></div>").text(d).addClass("toast-item").addClass(c);e.append(k);k.on("click",
function(){b(k)});a(function(){b(k)},f||3E3)}return{notify:function(a,b){d("NOTIFY",a,b)},success:function(a,b){d("SUCCESS",a,b)},error:function(a,b){d("ERROR",a,b)},empty:function(){var a=angular.element(document.querySelector(".toast-stack"));a&&a.empty()}}}])})();
