// *****************************************************************************
// Copyright (c) 2014, 2015, 2016, 2017 Pay With Privacy, Inc. All rights reserved.
// Authors:
// Jason Kruse   (jason@privacy.com)
// David Nichols (david@privacy.com)
// Boling Jiang  (boling@privacy.com)
// Felippe Nardi (felippe@privacy.com)
// *****************************************************************************
var environment="production",extensionVersion="";try{extensionVersion=chrome.runtime.getManifest().version,"beta"===environment&&chrome.browserAction.setBadgeText({text:extensionVersion})}catch(a){}var pwp=new Entity("background"),api=new Api;function g_openTab(a){chrome.tabs.query({active:!0},function(b){for(var c in b){var d=b[c];if(d.url.match(HOST_REGEX))return chrome.tabs.update(d.id,{url:a})}pwp.log("No active tabs. Opening a new one");return chrome.tabs.create({url:a})})}
var HOST_REGEX=/localhost|privacycard\.co|privacy\.com/i,g_id={};function g_getID(){return g_id.user?g_id.user:g_id.browser?g_id.browser:"-"}pwp.register("preCreateCard",function(a,b){pwp.log("Creating pre create");api.preCreateCard(a,b)});pwp.register("createVirtualCard",function(a,b){pwp.log("Creating Card for amount:"+a.amount);api.createVirtualCard(a,b)});pwp.register("user",function(a,b){api.user(a,b)});
pwp.register("getCardList",function(a,b){pwp.log("Getting card list. params=",a);api.getCardList(a,b)});pwp.register("setCardAttributes",function(a,b){pwp.log("Setting card attributes for cardID:"+a.cardID);api.setCardAttributes(a,b)});pwp.register("login",function(a,b){g_id.browser&&(a.browserID=g_id.browser);api.login(a,b)});pwp.register("tfa",function(a,b){api.tfa(a,b)});pwp.register("oneTimeCode",function(a,b){api.oneTimeCode(a,b)});
pwp.register("signup",function(a,b){g_id.browser&&(a.browserID=g_id.browser);api.signup(a,b)});pwp.register("logout",function(a,b){pwp.log("Logging out");api.logout(b)});pwp.register("addcreditcard",function(a,b){pwp.log("Adding credit card");api.addcreditcard(a,b)});pwp.register("fundlist",function(a,b){pwp.log("Getting fund list");api.fundlist(a,b)});pwp.register("bankAccountlist",function(a,b){pwp.log("Getting bank account list");api.bankaccountlist(a,b)});
pwp.register("openTab",function(a,b){pwp.log("Opening tab to "+a);g_openTab(a)});pwp.register("get",function(a,b){pwp.log("Getting: "+a);Store.get(a,b)});pwp.register("set",function(a,b){var c;for(c in a){var d=a[c];break}c&&d&&(pwp.log("Setting: "+c+"="+d),"userID"==c&&(0<d.length?g_id.user=d:delete g_id.user),Store.set(c,d,b))});pwp.register("remove",function(a,b){pwp.log("Removing: "+a);Store.remove(a,b)});
pwp.register("event",function(a){var b=a.name;a=void 0===a.data?{}:a.data;pwp.log("Sending event");api.sendEvent({event:{name:b,data:a}},function(){})});pwp.register("resize",function(a){});pwp.register("opentab",function(a){});
Store.get("userID",function(a){a?g_id.user=a:Store.get("browserID",function(a){if(a)g_id.browser=a;else{for(a="";32>a.length;)a+=Math.random().toString(32).replace(/[^a-z]+/g,"");a=a.substr(0,32);pwp.log("Generated browserID: "+a);Store.set("browserID",a,function(){g_id.browser=a})}})});chrome.runtime.onInstalled.addListener(function(a){"update"===a.reason&&Store.set("showTooltipFlag",!0)});pwp.register("opentab",function(a){pwp.log("Opening tab to "+a);g_openTab(a)});
pwp.register("getExtensionHref",function(a,b){pwp.log("Getting Extension ID");b(chrome.extension.getURL("/"))});
