// *****************************************************************************
// Copyright (c) 2014, 2015, 2016, 2017 Pay With Privacy, Inc. All rights reserved.
// Authors:
// Jason Kruse   (jason@privacy.com)
// David Nichols (david@privacy.com)
// Boling Jiang  (boling@privacy.com)
// Felippe Nardi (felippe@privacy.com)
// *****************************************************************************
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,m,r){d instanceof String&&(d=String(d));for(var q=d.length,t=0;t<q;t++){var y=d[t];if(m.call(r,y,t,d))return{i:t,v:y}}return{i:-1,v:void 0}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(d,m,r){d!=Array.prototype&&d!=Object.prototype&&(d[m]=r.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};
$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,m,r,q){if(m){r=$jscomp.global;d=d.split(".");for(q=0;q<d.length-1;q++){var t=d[q];t in r||(r[t]={});r=r[t]}d=d[d.length-1];q=r[d];m=m(q);m!=q&&null!=m&&$jscomp.defineProperty(r,d,{configurable:!0,writable:!0,value:m})}};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,r){return $jscomp.findInternal(this,d,r).v}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var m=0;return $jscomp.iteratorPrototype(function(){return m<d.length?{done:!1,value:d[m++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.iteratorFromArray=function(d,m){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var r=0,q={next:function(){if(r<d.length){var t=r++;return{value:m(t,d[t]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6-impl","es3");var trimString=function(d){return d.trim().replace(/\s\s+/g," ")};mode=function(d){if(0===d.length)return null;for(var m={},r=d[0],q=1,t=0;t<d.length;t++){var y=d[t];null==m[y]?m[y]=1:m[y]++;m[y]>q&&(r=y,q=m[y])}return r};intersect=function(d,m){return d.filter(function(d){return-1!==m.indexOf(d)})};
var IS_FIREFOX=/Firefox\//.test(navigator.userAgent),_log=console.log;console.log=function(){var d=Array.prototype.slice.call(arguments),m=new Date,m=m.getHours()+":"+m.getMinutes()+":"+m.getSeconds();d.unshift("["+m+"] "+window.location.host+window.location.pathname+":");_log.apply(console,d)};
window.Checkout=function(){function d(a,b){if(0===a.length)return b.length;if(0===b.length)return a.length;var h=[],c;for(c=0;c<=b.length;c++)h[c]=[c];var e;for(e=0;e<=a.length;e++)h[0][e]=e;for(c=1;c<=b.length;c++)for(e=1;e<=a.length;e++)b.charAt(c-1)==a.charAt(e-1)?h[c][e]=h[c-1][e-1]:h[c][e]=Math.min(h[c-1][e-1]+1,Math.min(h[c][e-1]+1,h[c-1][e]+1));return h[b.length][a.length]}function m(a){try{for(var b=["mouseover","mousedown","mouseup","click"],h=0;h<b.length;h++)a.dispatchEvent(new MouseEvent(b[h],
{bubbles:!0,cancelable:!0,view:window}))}catch(c){}}function r(a,b){$parentsa=$(a).parents();$parentsb=$(b).parents();var h=null;$parentsa.each(function(){var a=this;$parentsb.each(function(){if(a==this)return h=this,!1});if(h)return!1});return h}function q(a){if(0===a.length)return{};if(a.data().attr)return a.data().attr;var b=function(c){255<c.label.length&&(c.label="");255<c.value.length&&(c.value="");a.data("attr",c);return c},h="type id class maxlength value autocomplete size tabindex placeholder pattern title".split(" "),
c={};c.tag=a[0].tagName.toLowerCase();for(var e in h){var k=h[e],n=a.attr(k)||"";c[k]=n}e=a.attr("name")||"";(h=e.match(/_?D?:?\/atg\/commerce.*\.(.*)/i))&&2===h.length&&(e=h[1]);c.name=e;c.label="";if(a.attr("name"))try{var d=a.attr("name");labelText=trimString($("label[for='"+d+"']").text());if(0<labelText.length)return c.label=labelText,b(c)}catch(X){}if(0<trimString(a.closest("label").text()).length)return c.label=trimString(a.closest("label").text()),b(c);d=a.parent();for(e=1;10>=e;e++){if(1==
d.find("label").length&&1==d.find("input, select").not('input[type="hidden"]').length)return e=d.find("label"),0<trimString(e.text()).length?c.label=trimString(e.text()):0<trimString(e.attr("alt")||"").length?c.label=trimString(e.attr("alt")):0<trimString(e.attr("placeholder")||"").length?c.label=trimString(e.attr("placeholder")):c.label="",b(c);d=d.parent()}d=a.parent();h=/^([^a-z]+|required|.?what\'s\s+this.?)$/i;k=+new Date;for(e=1;10>=e&&!(1<d.find("input, select").not('input[type="hidden"],input[readonly],input[disabled]').filter(function(a,
c){var b=c.getBoundingClientRect();return 0<b.width&&0<b.height}).length);e++){n=t(d);if(0<n.length&&!h.test(n)){c.label=n;break}d=d.parent();if(100<+new Date-k)break}return b(c)}function t(a){$eleCloned=a.clone();$eleCloned.find("iframe, script, style").remove();return trimString($eleCloned.text())}function y(a){a&&$("._pwp-icon").remove();0<$("iframe#pwp_interstitial").length?$("#pwp_interstitial").remove():window!=window.top&&window.top.postMessage({invoke:"closeCreateCard"},"*");$("._pwp-icon").css({});
document.body.style.overflowY=M}function p(a,b){b=b||"";if(a)if(Array.isArray(a)||(a=[a]),1==a.length&&a[0].is("iframe"))a[0][0].contentWindow.postMessage({invoke:"populateIframeField",value:b},"*");else{var h=function(a,c){a.dispatchEvent(new KeyboardEvent(c,{bubbles:!0,cancelable:!0,composed:!0,"char":"4",key:"4",code:"Digit4",keyCode:52,which:52,altKey:!1,shiftKey:!1,ctrlKey:!1}))},c=function(a,c){a.dispatchEvent(new Event(c,{bubbles:!0,cancelable:!1,composed:!1}))},e;for(e in a){$field=a[e];var k=
/^[*0-9]{16}$/,n=/mm\/y{2,4}/i;if($field.is("select")||!(0<$field.val().trim().length)||k.test($field.val().trim())||-1!==$field.val().indexOf("*")||n.test($field.val().trim())||$field.val()==$field.attr("placeholder"))k=$field[0],$field.is("input")?(k.focus(),h(k,"keydown"),h(k,"keypress"),$field.val(b),c(k,"input"),h(k,"keyup"),c(k,"change"),k.blur()):$field.is("select")?(k.focus(),$field.val(b),c(k,"change"),k.blur()):$field.val(b)}}}function O(a,b){a[0].dispatchEvent(new Event("chosen:updated"));
if(b){var h=a.find("option").first().text()||"";$maxP=a.parent();for(var c=0;10>c&&100>$maxP.outerWidth();c++)$maxP=$maxP.parent();c=V($maxP,h);if(0<h.length&&0<c.length)c.text(b);else if(1!=a.siblings().length||a.siblings().is("select, input")){$p=a.parent();for(var e=/visa|^jan|^feb|^mar|^apr|^may|^jun|^jul|^aug|^sep|^oct|^nov|^dec|^[0-9]{1,4}$/i,k=!1;$p[0]!=$maxP[0]&&!k;){for(var n=$p[0].attributes,c=0;c<n.length;c++){var d=n[c];if(/^data\-/i.test(d.name)&&(e.test(d.value)||(d.value||"").toUpperCase()==
h.toUpperCase())){$p.attr(d.name,b);k=!0;break}}$p=$p.parent()}}else{var g=a.siblings();console.info("POSTPROCESS","Possible label=",g.text());(h=g.find("*:not(:has(*))").toArray().filter(function(a){return $(a).text().trim()==g.text().trim()}).shift())&&(g=$(h));20>g.text().trim().length&&g.text(b)}}}function D(a,b){return a.find(":not(iframe, script, style, select, option)").contents().filter(function(){return 3==this.nodeType&&b.test(this.textContent)}).parent()}function V(a,b){return a.find(":not(iframe, script, style, select, option)").contents().filter(function(){return 3==
this.nodeType&&0===this.textContent.indexOf(b)}).parent()}function C(a){a?window.top.postMessage({invoke:"dismissTooltip"},"*"):($("#pwp_tooltip").remove(),$("#pwp_tooltipArrow").remove())}function W(a){if(3<=$("iframe#braintree-hosted-field-number, iframe#braintree-hosted-field-expirationMonth, iframe#braintree-hosted-field-expirationYear, iframe#braintree-hosted-field-cvv ").length)return g.pan=[$("iframe#braintree-hosted-field-number")],g.cvv=[$("iframe#braintree-hosted-field-cvv")],g.expMonth=
[$("iframe#braintree-hosted-field-expirationMonth")],g.expYear=[$("iframe#braintree-hosted-field-expirationYear")],u=!0,a(u);if(3<=$('input[data-stripe="number"], input[data-stripe="exp"], input[data-stripe="cvc"]').length)return g.pan=[$('input[data-stripe="number"]')],g.cvv=[$('input[data-stripe="cvc"]')],g.expDate=[$('input[data-stripe="exp"]')],u=!0,a(u);if(/pge\.com|doxs\.net/.test(window.location.host)&&0<$("#txtDebitCreditNumberNofld").length)return g.pan=[$("#txtDebitCreditNumberNofld")],
u=!0,a(u);if(/brownpapertickets\.com/i.test(window.location.host)&&$("#cc"))return g.pan=[$("#cc")],g.cvv=[$('input[name="code"]')],g.expMonth=[$("select#month")],g.expYear=[$("select#year")],u=!0,a(u);if(/jetcopg\.com/i.test(window.location.host)&&4==$('input[name="cNoTxt1"],input[name="cNoTxt2"],input[name="cNoTxt3"],input[name="cNoTxt4"]').length)return g.pan=[$('input[name="cNoTxt1"]'),$('input[name="cNoTxt2"]'),$('input[name="cNoTxt3"]'),$('input[name="cNoTxt4"]')],g.cvv=[$('input[name="cardVerificationNumber"]')],
g.expMonth=[$('select[name="expiryMonth"]')],g.expYear=[$('select[name="expiryYear"]')],N=u=!0,a(u);if(/qvc\.com/i.test(window.location.host)&&$("#txtNewCardNumber"))return g.pan=[$("#txtNewCardNumber")],g.cvv=[$("#txtSecurityCode")],g.expDate=[$("#selNewCard")],u=!0,a(u);H=$("input[type!='radio'], select");var b=JSON.parse(JSON.stringify(x));I(b,function(b){if(!b.pan||0===b.pan.length)return a(!1);b=g.expMonth&&0<g.expMonth.length&&g.expYear&&0<g.expYear.length||g.expDate&&0<g.expDate.length;u=g.pan&&
0<g.pan.length&&b;a(u)})}function J(a){var b={};b.width=b.height=Math.min(150,Math.max(20,Math.round(.7*a.outerHeight())));b.top=a.position().top+parseInt(a.css("margin-top")||0)+a.outerHeight()/2-b.height/2;var h=0<parseInt(a.css("padding-right"))?parseInt(a.css("padding-right"))/2:parseInt(a.css("padding-left"))/2;b.left=a.position().left+a.innerWidth()-b.width-h;return b}function P(a,b,h){var c=!1;if(a)var e=function(a){var c=0;try{var e=a.attr("src")||"";-1!==e.indexOf(b.location.pathname)&&c++;
-1!==e.indexOf(b.location.hostname)&&c++;if(h)var d=h.filter(function(a){return-1!==e.indexOf(a)}),c=c+3*d.length;a.width()==b.dimensions.width&&c++;a.height()==b.dimensions.height&&c++;return c}catch(Y){}},c=$("iframe, frame").toArray().sort(function(a,c){return e($(c))-e($(a))}).shift();return c}function Q(a,b,h,c){(a=P(a,b))&&$(a).addClass("_pwp_checkout_frame");pwp.invoke("getExtensionHref",{},function(a){var b=$("<iframe />"),e=chrome.extension.getURL("/interstitial.html"),d=!0,g=h.left-345;
0>g&&(g=h.left+24,d=!1);b.attr("id","pwp_interstitial").attr("src",e).css({all:IS_FIREFOX?"":"unset","z-index":2147483645,position:"fixed",left:"0",top:"0",display:"block",width:"100vw",height:"100vh","background-color":"transparent",border:"0"}).load(function(){var b={caller:window.location.protocol+"//"+window.location.host,useParent:c,interstitialOnLeft:d};$(this)[0].contentWindow.postMessage(b,a);$(this)[0].style.setProperty("width","100vw","important");$(this)[0].style.setProperty("height","100vh",
"important");$(this)[0].style.setProperty("display","block","important")}).topZIndex();0===$("body").length&&$("frameset").wrap("<body />");$("body").append(b);$("body").on("click",function(a){y();$("body").off("click")})})}function R(a){var b=!1,d=window!=window.top,c=function(){C(d)};if(!a.data("_pwp_card_id")){a.data("_pwp_card_id","true");var e=J(a);$cardNumParent=a.parent().append($("<img />").css({all:IS_FIREFOX?"":"unset",position:"absolute",cursor:"pointer",left:e.left||0,top:e.top||0,"z-index":2147483646,
width:e.width||0,height:e.height||0,"border-radius":"2px","box-shadow":"0 2px 4px rgba(0,0,0,0.2)",transition:"all .25s"}).attr({src:"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cGF0aCBmaWxsPSIjRkZGIiBkPSJNMCAwaDMydjMySDB6Ii8+PHBhdGggZD0iTTMyIDB2MzJIMFYwaDMyek0xNS42NDggOEg5LjZ2MTYuMDM4aDMuNDM2di01LjI3aDIuNjEyYzQuNjEzIDAgNi45MTktMS43OTQgNi45MTktNS4zODMgMC0zLjU5LTIuMzA2LTUuMzg0LTYuOTE5LTUuMzg0em0uMTYgMy4wMjVjMi4xNyAwIDMuMjU0Ljc4NiAzLjI1NCAyLjM2IDAgMS41NzMtMS4wODUgMi4zNi0zLjI1MyAyLjM2aC0yLjc3M3YtNC43MnoiIGZpbGw9IiMyMzIzMjAiLz48L2c+PC9zdmc+",
"class":"_pwp-icon",alt:"Checkout with Privacy",title:"Checkout with Privacy"}));$("._pwp-icon").off("click").on("click",function(a){if(!b){b=!0;setTimeout(function(){b=!1},2E3);var c=$(this);if(!a.originalEvent||!a.originalEvent.hasOwnProperty("isTrusted")||a.originalEvent.isTrusted){$("._pwp-icon").css({});a=c[0].getBoundingClientRect();if(!d){c=g.pan[0];var e=!1;c.parents().each(function(){if($(this).is("body"))return!1;if("fixed"===$(this).css("position"))return e=!0,!1})}d&&window.parent!=window.top?
Q(!1,e,a,!0):window.top.postMessage({invoke:"openCreateCard",iframe:d,frameInfo:d?{location:JSON.parse(JSON.stringify(window.location)),dimensions:{width:window.innerWidth,height:window.innerHeight}}:e,iconOffset:{left:a.left,top:a.top}},"*");M=document.body.style.overflowY;document.body.style.overflowY="hidden"}}});$("._pwp-icon").hover(function(a){pwp.invoke("get","showTooltipFlag",function(c){c?S(a):C(d)})},c);a.data("lastLeft",a.position().left);a.data("lastTop",a.position().top);a.on("paste keyup",
function(a){var b=$(this);setTimeout(function(){var a=b.val().length;4<=a&&!b.data("hiding")?(b.data("hiding",!0),b.parent().find("._pwp-icon").css({opacity:"0"}),c(),b.data("hiding",!1)):0!==a||b.data("showing")||(b.data("showing",!0),b.parent().find("._pwp-icon").css({opacity:"1"}),b.data("showing",!1))},0)});pwp.invoke("event",{name:"Extension: Detected Checkout Form"})}}function T(a){if(a.attr("id")&&0<a.attr("id").length)return"#"+a.attr("id");if(a.attr("name")&&0<a.attr("name").length){var b=
a[0].tagName.toLowerCase();a=a.attr("name");return b+'[name="'+a+'"]'}return!1}function S(a){var b=window!=window.top;var d=a?a.currentTarget.getBoundingClientRect():$("._pwp-icon")[0].getBoundingClientRect();var c=!1;g.pan[0].parents().each(function(){if($(this).is("body"))return!1;if("fixed"===$(this).css("position"))return c=!0,!1});var e=0<d.width&&(0<d.left||0<d.top);pwp.invoke("get","showTooltipFlag",function(a){a&&e&&window.top.postMessage({invoke:"createTooltip",iframe:b,frameInfo:b?{location:JSON.parse(JSON.stringify(window.location)),
dimensions:{width:window.innerWidth,height:window.innerHeight}}:c,iconOffset:{left:d.left,top:d.top}},"*")})}var x={pan:{required:!0,rules:[{regex:/((card|cc|pay).*(num|#))|creditcard|^pan|AuthorizeNet_ccno|^cc$|^cnb$/i},{braintree:"number"},{panLike:1}]},cvv:{required:!0,rules:[{regex:/cvv|cid|csc|cvd|cvn|cvc|ccv|spc|signature.*panel|secure.*id|sec(urity)?.*code|account.*verification|card.*verification|verification.*(code|number)|credit.*card.*code|security.*number|card.*extra.*code/i},{cvvLength:1}]},
expMonth:{required:!1,rules:[{regex:/((exp|card|cc).*(mo|mm))|^mm$|^month$/i},{braintree:"expiration_month"},{hasMonth:1}]},expYear:{required:!1,rules:[{regex:/((exp|card|cc).*(year|yr|yy))|^y{2,4}$|^year$/i},{braintree:"expiration_year"},{hasYear:1}]},expDate:{required:!1,rules:[{regex:/((card|cc).*(exp|date))|(exp.*date)|(mm ?\/ ?yy)/i}]}},H=[],g={},u=!1,K=!1,N=!1,M="",I=function(a,b){var d=Object.keys(a);if(0===d.length)return b(g);var c=d.shift(),e=[];(function(a,c,b){var e=a.concat();setTimeout(function A(){c(e.shift());
0<e.length?setTimeout(A,0):b()},0)})(H.toArray(),function(a){a=$(a);var b=function(a,b){return-1!==(a||[]).map(function(a){return a[0]}).indexOf(b[0])};if(!b(g.pan,a)&&!b(g.cvv,a)&&(a.is("input")||"pan"!=c&&"cvv"!=c)){var b=q(a),d=[],h;for(h in x[c].rules){var k,m=x[c].rules[h],f=!1;if(!window.location.host.match(/paypal\.com/)){for(k in b)if(b[k].match(/gift.?card|rewards?.?card|redeemable.?card|payGCNum/i)){f=!0;break}else if(a.is("select")&&200<a.find("option").length){f=!0;break}else if(b[k].match(/routing.?number/i)){f=
!0;break}else if("class"!==k&&b[k].match(/address/i)){f=!0;break}else if(b[k].match(/company/i)){f=!0;break}else if(b[k].match(/issuenumber/i)){f=!0;break}if(f)break}if(f)return;if("regex"in m)for(k in b){if(b[k].match(m.regex)){if("pan"==c){if(b[k].match(x.cvv.rules[0].regex))continue;if(b[k].match(/account.?number/i))continue;if(b[k].match(/promo/i))continue}else if("expDate"==c){var f=/mm ?\/ ?yy/i,p=/american.?express/i;if(b.maxlength&&4>parseInt(b.maxlength))break;else if(b.size&&4>parseInt(b.size))break;
else if(!f.test(b[k])&&x.expMonth.rules[0].regex.test(b[k]))continue;else if(!f.test(b[k])&&x.expYear.rules[0].regex.test(b[k]))continue;else if(p.test(b[k]))continue}else if("expMonth"===c&&b[k].match(x.expYear.rules[0].regex))continue;else if("expYear"==c&&b[k].match(x.expMonth.rules[0].regex))continue;d.push(k)}}else if("braintree"in m)a.data("braintree-name");else if("hasMonth"in m)a.is("select")&&(12==a.find("option").length||13==a.find("option").length||a.find("option").first().text().match(x.expMonth.rules[0]))&&
d.push("hasMonth");else if("hasYear"in m){if(a.is("select")){var l=!1,L=(new Date).getFullYear().toString().substr(2,2);a.find("option").toArray().every(function(a){return 0<=$(a).text().indexOf(L)?(l=!0,!1):!0});l&&d.push("hasYear")}}else if("cvvLength"in m){if(4==b.maxlength||4==b.size)/exp|date/i.test((b.id||"")+(b.name||"")+(b.label||""))||d.push("cvvLength")}else"panLike"in m&&16==(b.placeholder||"").replace(/[^0-9]/g,"").length&&d.push("panLike")}0<d.length&&e.push({ele:a,matches:d,attr:b})}},
function(){var d=function(c,d){delete a[c];g[c]=d;I(a,b)},h=function(a){return $("iframe").toArray().filter(function(b){b=$(b).attr("src")||"";return a.test(b)?!0:!1})};if("pan"==c){if((h=h(/moneris\.com|hostedpci\.com/i))&&0<h.length)return e=h.map(function(a){return $(a)}),d(c,e)}else if("cvv"==c&&(h=h(/hostedpci\.com/i))&&0<h.length)return e=h.map(function(a){return $(a)}),d(c,e);if(1<e.length){var m={};e.forEach(function(a){a.matches.forEach(function(b){-1===Object.keys(m).indexOf(b)&&(m[b]=[]);
a.attr[b]&&0<a.attr[b].length&&m[b].push(a.attr[b]||"")})});var p={};Object.keys(m).filter(function(a){return-1===["label","cvvLength","hasYear","hasMonth"].indexOf(a)}).forEach(function(a){var b=m[a];if(1>=b.length)b="";else if(b=b||[],0===b.length)b="";else{for(var c=b.concat().sort(),b=c[0],c=c[c.length-1],d=b.length,e=0;e<d&&b.charAt(e)===c.charAt(e);)e++;b=b.substring(0,e)}5<b.length&&(p[a]=b)});var q="pan"==c?/(pan)|(number)/i:x[c].rules[0].regex,r="pan"==c?x.cvv.rules[0].regex:!1;var f=e.concat();
Object.keys(p).forEach(function(a){var b=p[a];f.forEach(function(c,e,d){if(-1!==c.matches.indexOf(a)){var h=c.attr[a].replace(b,""),h=r?q.test(h)&&!r.test(h):q.test(h);-1!==c.matches.indexOf("hasMonth")||-1!==c.matches.indexOf("hasYear")||-1!==c.matches.indexOf("cvvLength")||h||(c.matches=c.matches.filter(function(b){return b!=a}),d[e]=c)}})});f=f.filter(function(a){return 0<a.matches.length});0<f.length&&(e=f)}if("pan"===c||"cvv"===c)if(f=e.filter(function(a){$cardNum=$(a.ele);if("pan"===c){if($cardNum.attr("type")&&
"text"!=$cardNum.attr("type").toLowerCase()&&"number"!=$cardNum.attr("type").toLowerCase()&&"password"!=$cardNum.attr("type").toLowerCase()&&"tel"!=$cardNum.attr("type").toLowerCase()||$cardNum.attr("maxLength")&&16>parseInt($cardNum.attr("maxLength"))||0>=$cardNum.outerHeight())return!1}else if($cardNum.attr("type")&&"text"!=$cardNum.attr("type").toLowerCase()&&"number"!=$cardNum.attr("type").toLowerCase()&&"tel"!=$cardNum.attr("type").toLowerCase()&&"password"!=$cardNum.attr("type").toLowerCase())return!1;
return!0}),0<f.length&&(e=f),1<e.length&&(f=e.filter(function(a){return a.matches.reduce(function(b,e){return"pan"===c?b&&!/name|owner|cvv|bank|phone|zip|postal|bankaccount/i.test(a.attr[e]):b&&!/name|owner|bank|phone|zip|postal/i.test(a.attr[e])},!0)}),0<f.length&&(e=f)),"pan"==c&&4<=e.length){var t={},l={};f=e.filter(function(a){var b=4==a.attr.maxlength||4==a.attr.size;b&&(a=a.ele[0].getBoundingClientRect(),t[a.width]=(t[a.width]||0)+1,l[a.top]=(l[a.top]||0)+1);return b});4<=f.length&&(secondFilteredCandidates=
f.filter(function(a){a=a.ele[0].getBoundingClientRect();if(2*t[a.width]>f.length||2*l[a.top]>f.length)return!0}),4==secondFilteredCandidates.length&&(N=!0,e=secondFilteredCandidates.sort(function(a,b){return a.ele[0].getBoundingClientRect().left-b.ele[0].getBoundingClientRect().left})))}else"pan"===c&&(f=e.filter(function(a){return a.attr.size&&4>=a.attr.size||a.attr.maxlength&&4>=a.attr.maxlength?!1:!0}),0<f.length&&(e=f));else"expMonth"===c?1<e.length&&(e=e.filter(function(a){a=a.ele;return a.is("select")&&
14<a.find("option").length?!1:!0}),f=e.filter(function(a){a=a.ele;if(!a.is("select"))return!0;for(var b=0;b<a.find("option").length;b++){var c=$(a.find("option")[b]).text().trim();if("01"===c||"1"===c||c.match(/jan/i))return!0}return!1}),0<f.length&&(e=f),1<e.length&&(f=e.filter(function(a){return a.matches.reduce(function(b,c){return b&&!(a.attr[c]||"").match(/year/i)},!0)}),0<f.length&&(e=f))):"expDate"===c&&(e=e.filter(function(a){$expDate=$(a.ele);return $expDate.is("select")?!1:!0}));e=e.map(function(a){return a.ele});
if("pan"===c&&0===e.length)return b(g);if("pan"===c&&e.reduce(function(a,b){return a&&"hidden"===b.attr("type")},!0))return b([]);d(c,e)})},w={createInterstitial:Q,scanPage:function(a){if(u)return a(u);K=!0;W(function(b){if(b){var d=N?[g.pan[g.pan.length-1]]:g.pan,c;for(c in d)d=g.pan[c],"hidden"!==d.attr("type")&&"button"!==d.attr("type")&&R(d);S()}else window===window.top&&0===window.length&&C(!1);K=!1;a(b)})},updateUI:function(a){(void 0===a?0:a)&&C(!1);var b=!1,d,c;for(d in g.pan)if(a=g.pan[d],
c=T(a))c=$(c),0<c.length&&0<a.parent().find("._pwp-icon").length&&0===c.parent().find("._pwp-icon").length&&(b=!0,g.pan[d]=c,R(c));if(b)for(d in a=["cvv","expDate","expMonth","expYear"],a)for(e in b=a[d],g[b])if(c=T(g[b][e]))c=$(c),g[b][e]=c;for(d in g.pan){a=g.pan[d];c=a.data()||{};var e=J(a);if("lastTop"in c&&"lastLeft"in c&&(a.data("lastLeft")!=a.position().left||a.data("lastTop")!=a.position().top)){c={left:e.left,top:e.top,width:Math.max(20,e.width)};var b={left:e.left-130,top:e.top-55},k={left:e.left+
3,top:e.top-13};a.parent().find("._pwp-icon").css(c);$("body").find("#pwp_tooltip").css(b);$("body").find("#pwp_tooltipArrow").css(k);a.data("lastLeft",a.position().left);a.data("lastTop",a.position().top)}c=a;k=e;a=c.parent().find("._pwp-icon");e=c.position();(b=a.position())&&b.top&&20<Math.abs(e.top-b.top)&&(0<parseInt(c.css("padding-right"))?parseInt(c.css("padding-right")):parseInt(c.css("padding-left")),c=c.outerHeight()/2-k.height/2,e=e.top-b.top,e=parseInt(parseFloat(a.css("top"))+e+c),a.css({top:e}))}},
populateFields:function(a){var b,h;if(u){y(!0);a=new PaymentCard(a.pan||a.PAN,a.cvv||a.CVV,a.expMonth,a.expYear,a.billingStreet,a.billingCity,a.billingState,a.billingZip);var c=a.getYear(),e=c.toString().substr(-2,2),k=a.getMonth(),n=$("select").find("option").filter(function(){$opt=$(this);return $opt.text().match(a.network.getRegex())||$opt.val().match(a.network.getRegex())}).toArray().sort(function(b,c){return d($(b).text(),a.network.getString())>d($(c).text(),a.network.getString())}).shift();
if(n){var n=$(n),v=n.closest("select");p(v,n.val());O(v,a.network.getString(!0))}(n=$('input[type="radio"]').filter(function(){var a=q($(this)).label||"";return a.match(/visa/i)&&!a.match(/visa\s*checkout/i)&&!a.match(/master\s*card/i)}).toArray().sort(function(a,b){return d(q($(a)).label,"visa")>d(q($(b)).label,"visa")}).shift())&&m(n);if(N)for(n=a.getPAN().match(/\d{4}/g),b=0;b<n.length;b++)p(g.pan[b],n[b]);else p(g.pan,a.getPAN());p(g.cvv,a.getCVV());if(g.expMonth&&0<g.expMonth.length&&g.expYear&&
0<g.expYear.length){b="_ignored_ Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");var w=["_ignored_",/jan/i,/feb/i,/mar/i,/apr/i,/may/i,/jun/i,/jul/i,/aug/i,/sep/i,/oct/i,/nov/i,/dec/i][k];var x=b[k];n="_ignored_ January February March April May June July August September October November December".split(" ")[k];var A=10>k?"0"+k:String(k);for(b=0;b<g.expMonth.length;b++){var f=g.expMonth[b];if(f.is("select")){var C=h=!1;f.find("option").each(function(a,b){var c=$(b);if(c.val().match(w)||
c.text().match(w))C=!0,h=c.text(),0<c.val().length?p(f,c.val()):c.prop("selected",!0)});if(!C)if(0<f.find('option[value="0"]').length&&0==f.find('option[value="12"]').length&&k--,0<f.find('option[value="'+A+'"]').length)h=f.find('option[value="'+A+'"]').text(),p(f,A);else if(0<f.find('option[value="'+k+'"]').length)h=f.find('option[value="'+k+'"]').text(),p(f,String(k));else try{var l=f.children().length;$(f.children()[12==l?k-1:k]).prop("selected",!0);h=$(f.children()[12==l?k-1:k]).text()}catch(U){}O(f,
h)}else f.is("input")?f.attr("placeholder")&&/mm/i.test(f.attr("placeholder"))||f.attr("maxlength")&&2==f.attr("maxlength")?f.val(A):p(f,A):f.is("iframe")&&p(f,A)}for(b=0;b<g.expYear.length;b++)if(f=g.expYear[b],f.is("select")){h=!1;var L=RegExp(e+"$");f.find("option").each(function(a,b){var c=$(b);L.test(c.text().trim())&&(h=c.text(),0<c.val().length?p(f,c.val()):c.prop("selected",!0))});O(f,h)}else if(f.is("input")){if(f.attr("placeholder")&&/y{4}/i.test(f.attr("placeholder"))||f.attr("maxlength")&&
4==f.attr("maxlength"))f.val(c);else if(f.attr("placeholder")&&/y{2}/i.test(f.attr("placeholder"))||f.attr("maxlength")&&2==f.attr("maxlength"))f.val(e);else{l=f.parent();for(v=!1;!v&&255>trimString(l.text()).length&&5>l.find("input, select").length;){var z=t(l);/y{4}/i.test(z)?(p(f,c),v=!0):/y{2}/i.test(z)&&(p(f,e),v=!0);l=l.parent()}v||p(f,c);l="("+c+")|("+e+")";l=D($("body"),new RegExp("^"+l+"$"));0<l.length&&l.each(function(a,b){b.dispatchEvent(new Event("click",{bubbles:!0}))})}setTimeout(function(){f.val().substr(-2)!=
e&&f.val(c)},100)}else f.is("iframe")&&p(f,c);l=new RegExp(x,"i");var K=new RegExp("(^"+x+"$)|(^"+n+"$)","i");D($("body"),l).toArray().filter(function(a){a=$(a).text().replace(/[^a-zA-Z]/g,"");return K.test(a)}).forEach(function(a){var b=$(a).parent().is("li")&&(12==$(a).closest("ul").find("li").length||13==$(a).closest("ul").find("li").length);$(a).is("a")&&!b||m(a)});l=new RegExp(10>k?"(^0?"+k+"$)":"(^"+k+"$)");n=new RegExp("(^0?"+("1"==k?"2":"1")+"$)");v=new RegExp("(^"+("12"==k?"11":"12")+"$)");
l=D($("body"),l).toArray();n=D($("body"),n).toArray();v=D($("body"),v).toArray();if(0<l.length&&0<n.length&&0<v.length&&1E3>l.length*n.length*v.length){var E=!1;for(b=0;!E&&b<l.length;b++)for(z=0;!E&&z<n.length;z++)for(var F=0;!E&&F<v.length;F++){var G=r(l[b],n[z]),M=r(l[b],v[F]);G==M&&255>$(G).text().replace(/[^a-zA-Z0-9]/g,"").length&&(E=!0,$(l[b]).is("a")&&(E=-1!==($(G).text()||"").replace(/[\s0]/g,"").indexOf("12345678911112")),E&&m(l[b]),E=!0)}}L=new RegExp("(^\\s*"+e+"\\s*$)|(^\\s*"+c+"\\s*$)",
"i");D($("body"),L).each(function(a){a=new RegExp("(^\\s*"+(e-1)+"\\s*$)|(^\\s*"+(c-1)+"\\s*$)","i");0<D($(this).parent(),a).length&&m($(this)[0])})}if(g.expDate&&0<g.expDate.length)for(b=0;b<g.expDate.length;b++)f=g.expDate[b],l=q(f),n=10>k?"0"+k:k,v=/mm\s*\/\s*yy/i,z=/mm\s*\/\s*yyyy/i,F=/mm\s?yy/i,G=/mm\s?yyyy/i,v.test(l.placeholder)&&!z.test(l.placeholder)||v.test(l.label)&&!z.test(l.label)||5==l.maxlength||5==l.size?p(f,n+"/"+e):z.test(l.placeholder)||z.test(l.label)?p(f,n+"/"+c):F.test(l.placeholder)||
F.test(l.label)||4==l.maxlength||4==l.size?p(f,n+""+e):G.test(l.placeholder)||G.test(l.label)||6==l.maxlength||6==l.size?p(f,n+""+c):p(f,n+"/"+c);g.billingStreet&&p(g.billingStreet,a.getStreet());g.billingCity&&p(g.billingCity,a.getCity());if(g.billingState)try{var B=g.billingState[0];if(B.options){l=-1;n=1E6;billingState=a.getState();for(b in B.options)if(B.options[b].value){var H=B.options[b].value,I=B.options[b].text,J=Math.min(d(H,billingState["long"]),d(H,billingState["short"]),d(I,billingState["long"]),
d(I,billingState["short"]));J<n&&(n=J,l=b)}pwp.log("winner: "+B.options[l].value+" -- "+B.options[l].text);p(g.billingState,B.options[l].value)}else p(g.billingState,a.getState()["short"])}catch(U){pwp.log("Ignoring failure of billing state. Error: "+U)}g.billingZip&&p(g.billingZip,a.getZip());/amazon\.com$/.test(window.location.host)&&$(".a-dropdown-prompt").each(function(a,b){var d=$(b),e=parseInt(d.text());isNaN(e)||(12>=e&&d.text(k),2E3<e&&2100>e&&d.text(c))});/zazzle\.com$/i.test(window.location.host)&&
($("#page_paymentOptionForm_elements_creditCardForm_elements_expMonth_selector-displayName").text(A),$("#page_paymentOptionForm_elements_creditCardForm_elements_expYear_selector-displayName").text(c));$('ul[role="listbox"]').find("li").each(function(a){a=$(this);var b=a.text().trim().toLowerCase();b==c||b==e?a[0].dispatchEvent(new Event("mouseup")):b==k||b==A||b==x.toLowerCase()?a[0].dispatchEvent(new Event("mouseup")):"visa"==b&&a[0].dispatchEvent(new Event("mouseup"))});/fab\.com/i.test(window.location.host)&&
(g.pan[0][0].dispatchEvent(new Event("blur")),g.cvv[0][0].dispatchEvent(new Event("blur")),g.expMonth[0][0].dispatchEvent(new Event("blur")),g.expYear[0][0].dispatchEvent(new Event("blur")))}else 0<$("iframe").length&&(B=window.location.protocol+"//"+window.location.host,$("iframe")[0].contentWindow.postMessage({invoke:"populateFields",card:a},B))},removeCreateCardUI:y,showInterstitialError:function(a,b){pwp.invoke("getExtensionHref",{},function(d){try{$("iframe#pwp_interstitial")[0].contentWindow.postMessage({error:a,
status:b},d)}catch(c){}})},showInterstitialSubscription:function(a){pwp.invoke("getExtensionHref",{},function(b){try{$("iframe#pwp_interstitial")[0].contentWindow.postMessage({subscriptionRequired:a},b)}catch(h){}})},showInterstitialTFA:function(a){pwp.invoke("getExtensionHref",{},function(b){try{$("iframe#pwp_interstitial")[0].contentWindow.postMessage({tfa:a},b)}catch(h){}})},createTooltip:function(a,b,d){pwp.invoke("remove","showTooltipFlag");if(0===$("#pwp_tooltip").length&&window.parent===window.top){a=
P(a,b,["number"]);var c=!1;a?($(a).parents().each(function(){if($(this).is("body"))return!1;if("fixed"===$(this).css("position"))return c=!0,!1}),b=a.getBoundingClientRect()):(c=b,b={left:0,top:0});d.left+=b.left+(c?0:window.scrollX);d.top+=b.top+(c?0:window.scrollY);b=$("<div />");b.attr("id","pwp_tooltip").css({all:IS_FIREFOX?"":"unset","z-index":2147483645,position:c?"fixed":"absolute",left:d.left-135,top:d.top-52,width:275,height:30,"padding-top":12,"background-color":"#39F","text-align":"center",
"margin-top":"2px","border-radius":"8px","font-size":"12px",color:"white",transition:"all .25s",border:"0"}).topZIndex();$(b).append('<p style="all: unset; color: white; font-size: 12px; margin-top: 10px;"> Here\'s how the new Privacy icon looks! </p>');d=$("<div />)").attr("id","pwp_tooltipArrow").css({position:c?"fixed":"absolute",left:d.left+3,top:d.top-10,display:"block",height:"0",width:"0",border:"10px solid","border-color":"#39F transparent transparent","z-index":2147483645,transition:"all .25s"});
0===$("body").length&&$("frameset").wrap("<body />");$("body").append([b,d])}},dismissTooltip:C,foundCheckout:function(){return u},currentlyScanning:function(){return K},returnCandidates:function(){return g}};Checkout.createInterstitial=w.createInterstitial;Checkout.scanPage=w.scanPage;Checkout.updateUI=w.updateUI;Checkout.populateFields=w.populateFields;Checkout.removeCreateCardUI=w.removeCreateCardUI;Checkout.showInterstitialError=w.showInterstitialError;Checkout.showInterstitialSubscription=w.showInterstitialSubscription;
Checkout.showInterstitialTFA=w.showInterstitialTFA;Checkout.foundCheckout=w.foundCheckout;Checkout.currentlyScanning=w.currentlyScanning;Checkout.returnCandidates=w.returnCandidates;Checkout.createTooltip=w.createTooltip;Checkout.dismissTooltip=w.dismissTooltip;return w};
