// *****************************************************************************
// Copyright (c) 2014, 2015, 2016, 2017 Pay With Privacy, Inc. All rights reserved.
// Authors:
// Jason Kruse   (jason@privacy.com)
// David Nichols (david@privacy.com)
// Boling Jiang  (boling@privacy.com)
// Felippe Nardi (felippe@privacy.com)
// *****************************************************************************
var IS_SAFARI="undefined"!==typeof safari,port="undefined"!==typeof self&&"undefined"!==typeof self.port?self.port:void 0,pwp=new Entity("content",port),WHITELIST=/privacy\.com|localhost:9000/g,BLACKLIST=/raise\.com|gyft\.com|gmail\.com|mail\.google.com/g;
window.location.host.match(WHITELIST)||window.location.host.match(BLACKLIST)||$(function(){function d(){b.foundCheckout()||b.scanPage(function(a){})}function f(){var a=window.location.hostname;if("checkout.shopify.com"===a)return a=$("a.logo")[0],(a?a.hostname:window.location.host).replace(/^www\./,"");if("sites.fastspring.com"===a){var b=$("#logo a")[0];return(b?b.hostname:a).replace(/^www\./,"")}return a.replace(/^www\./,"")}pwp.log("Instantiating checkout for '"+document.title+"' ("+window.location.href+
")");var b=new Checkout,e=new Date(0),g=!1,h=!1,k=new Date(0);window.foundCheckout=!1;var l=function(a){if(a.data.invoke)switch(a.data.invoke){case "updateUI":b.updateUI(a.data.dismissTooltip);break;case "createTooltip":b.createTooltip(a.data.iframe,a.data.frameInfo,a.data.iconOffset);break;case "dismissTooltip":b.dismissTooltip();break;case "closeCreateCard":b.removeCreateCardUI(!1);break;case "openCreateCard":b.createInterstitial(a.data.iframe,a.data.frameInfo,a.data.iconOffset);break;case "populateFields":b.populateFields(a.data.card);
break;case "populateIframeField":if(1==$("input").length)$("input").val(a.data.value);else{var c=b.returnCandidates();(c=16===a.data.value.length?c.pan:c.cvv)&&0<c.length&&c.forEach(function(b){b.val(a.data.value)})}break;case "preCreateCard":pwp.invoke("preCreateCard",{hostname:f()},function(a){pwp.log("PreCreateCard Received");pwp.log(a);if(200===a.status){a.style||(a.hostname=f());pwp.invoke("getExtensionHref",{},function(b){try{$("iframe#pwp_interstitial")[0].contentWindow.postMessage({preCreateCard:a},
b)}catch(n){}});try{$("iframe#pwp_interstitial")[0].focus()}catch(m){}}else a.message?b.showInterstitialError(a.message,a.status):b.showInterstitialError("There was a server error. Please try again",a.status)});break;case "createCard":var c=a.data.card,d=""===c.hostname;c.hostname=f();var e=function(a){pwp.log("CreateCard Received");pwp.log(a);try{if(200===a.status&&a.card){b.removeCreateCardUI(!0);var c=a.card;c.expiration=a.card.expMonth+"/"+a.card.expYear.toString().substr(-2);c.created=+new Date;
var d=JSON.stringify(c);pwp.invoke("set",{card:d});pwp.log("Set cardJSON="+d);0<$("._pwp_checkout_frame").length?$("._pwp_checkout_frame")[0].contentWindow.postMessage({invoke:"populateFields",card:a.card},"*"):b.populateFields(a.card)}else 200===a.status&&a.userToken?b.showInterstitialTFA(a.userToken):401===a.status?b.showInterstitialError("Please login by clicking the P icon on the top right of your browser."):a.subscriptionRequired?b.showInterstitialSubscription(a.subscriptionRequired):a.message?
b.showInterstitialError(a.message):405===a.status?b.showInterstitialError("Woah there! You've got quite a few unused cards. Please use them first."):410===a.status?b.showInterstitialError("Add a funding source at privacy.com/funding to start creating cards."):b.showInterstitialError("There was a server error. Please try again")}catch(p){b.showInterstitialError("We ran into an error populating the checkout. Please view the card by clicking the Privacy logo in the right corner of your browser.")}};
c.cardID?(e({status:200,card:c}),(a.data&&a.data.modifiedExistingCard||d)&&pwp.invoke("setCardAttributes",c)):pwp.invoke("createVirtualCard",c,e)}};(new MutationObserver(function(a){if(!b.foundCheckout()&&!g){g=!0;a=new Date;var c=2500>a-e?2500-(a-e):0;var f=function(){b.currentlyScanning()?setTimeout(f,c):(d(),e=new Date,g=!1)};setTimeout(f,c)}b.foundCheckout()&&!h&&(h=!0,a=new Date,c=1E3>a-k?1E3-(a-k):0,setTimeout(function(){b.updateUI();k=new Date;h=!1},c))})).observe(document,{attributes:!0,childList:!0,
characterData:!0,subtree:!0});IS_SAFARI?setTimeout(d,1E3):(e=new Date,d());pwp.invoke("getExtensionHref",{},function(a){window.removeEventListener("message",l);window.addEventListener("message",l,!1)});$(window).resize(function(){b.updateUI(!0)});$(window).unload(function(){b.returnCandidates().pan&&window.top.postMessage({invoke:"updateUI",dismissTooltip:!0},"*")})});
WHITELIST.test(window.location.host)&&(window.addEventListener("message",function(d){d.data.invoke&&"extension::login"==d.data.invoke&&(pwp.invoke("set",{authToken:d.data.token}),pwp.invoke("set",{viewState:"MAIN"}))},!1),document.querySelector("body").setAttribute("data-extension-installed","1.5.0"));
