ZSH=/home/cxi/.config/zsh
alias reload="source $ZSH/zshrc"

autoload -U compinit;compinit


#SOURCE
source <(/usr/bin/starship init zsh --print-full-init)
source $ZSH/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#source $ZSH/colored-man-pages.plugin.zsh

# System Aliases
alias reboot='systemctl reboot'

# Coreutils ALiases
alias ls="exa -l -b -s modified --group-directories-first --git --icons"
alias la="exa -la "
alias lh="exa -la .*"

# Config Editing
alias efish="nvim ~/.config/fish/config.fish"
alias ezsh="nvim ~/.zshrc"
alias exonsh="nvim ~/.xonshrc"
alias enu="nvim ~/.config/nushell/config.nu"

alias evim="nvim ~/.config/nvim/init.vim"
alias envim="nvim ~/.config/nvim/init.lua"
alias eemacs="emacs ~/.emacs.d/init.el"
alias estar="nvim ~/.config/starship.toml"
alias ebat="nvim ~/.config/bat/config"

alias eqtile="nvim ~/.config/qtile/config.py"
alias esway="nvim ~/.config/sway/config"
alias ebspwm="nvim ~/.config/bspwm/bspwmrc"
alias espectrwm="nvim ~/.config/spectrwm/spectrwm.conf"
alias eawesome="nvim ~/.config/awesome/rc.lua"

alias esxhdk="nvim ~/.config/sxhkd/sxhkdrc"
alias epolybar="nvim ~/.config/polybar/config"
alias erofi="nvim ~/.config/rofi/config.rasi"
alias epicom="nvim ~/.config/picom/picom.conf"

alias eala="nvim ~/.config/alacritty/alacritty.yml"
alias ekitty="nvim ~/.config/kitty/kitty.conf"
alias etermi="nvim ~/.config/terminator/config"
alias ewez="nvim ~/.config/wezterm/wezterm.lua"


alias efstab="doas nvim /etc/fstab"
alias ersr="nvim ~/.local/bin/rsr" 
alias window_name="xprop |awk '/WM_CLASS/{print $4}'"

# One Letter Aliases
alias g="git"
alias c="cargo"
alias v="nvim"
alias e="emacsclient -c"


# Two Letter Aliases
alias nv="neovide --multigrid"
alias py="python3"



alias untar="tar -xvf"


export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'
